server:
  port: 8011
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%X{trace-id}] [%thread] %logger{15} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%X{trace-id}] [%thread] %logger{15} - %msg%n"
  level:
    com.q1sj: debug
